Fix undefined reference to a function which is unused when built with GPU and ROCM support
Linker error: undefined reference to `transpose_32x32_bits_reversed_diagonale_cpu'
would get thrown when building with hipified code. This commit hides that
function call behind a compiler flag when building with GPU and ROCM
support.